# --- [R65 - R66] --- #

    - name: Install necessary dependencies
      dnf:
        name:
          - dnf-plugins-core
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      dnf:
        name: https://download.docker.com/linux/centos/docker-ce.repo
        state: present

    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker configuration directory
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure Docker hardening options
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "icc": true,
            "userns-remap": "default",
            "no-new-privileges": true,
            "live-restore": true,
            "userland-proxy": false,
            "disable-legacy-registry": true,
            "log-level": "warn",
            "experimental": false,
            "insecure-registries": [],
            "max-concurrent-downloads": 3,
            "max-concurrent-uploads": 3
          }
        owner: root
        group: root
        mode: '0644'

# "icc": false: Disables inter-container communication.
# "userns-remap": "default": Enables user namespace remapping.
# "no-new-privileges": true: Prevents containers from gaining new privileges.
# "live-restore": true: Allows containers to continue running if the Docker daemon is restarted.
# "userland-proxy": false: Disables userland proxy for better performance and security.
# "disable-legacy-registry": true: Disables support for insecure legacy Docker registries.
# "log-level": "warn": Sets the logging level to "warn" to reduce log output.
# "experimental": false: Disables experimental features.
# "insecure-registries": []: Does not use any insecure registries.
# "max-concurrent-downloads": 3 and "max-concurrent-uploads": 3: Limits the number of concurrent downloads and uploads to reduce system load.

    - name: Restart Docker to apply changes
      systemd:
        name: docker
        state: restarted

# --- [R65 - R66] --- #
