# --- [R80] --- #

    - name: Ensure UFW is installed
      package:
        name: ufw
        state: present

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Set default policies to deny incoming and allow outgoing
      ufw:
        rule: default
        incoming: deny
        outgoing: allow

    - name: Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP traffic (if web server is needed)
      ufw:
        rule: allow
        name: 'Apache Full' # or 'Nginx Full' depending on your web server

    - name: Allow HTTPS traffic (if SSL/TLS is used)
      ufw:
        rule: allow
        name: 'Apache Secure' # or 'Nginx Secure' depending on your web server

    - name: Reload UFW to apply changes
      command: ufw reload

# --- [R80] --- #
