- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  ignore_errors: true

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
  ignore_errors: true
