    - name: Configure sysctl settings
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          # Memory settings
          vm.swappiness = 10
          vm.dirty_ratio = 20
          vm.dirty_background_ratio = 10

          # Kernel settings
          kernel.dmesg_restrict = 1
          kernel.kptr_restrict = 2
          kernel.yama.ptrace_scope = 1
          kernel.perf_event_paranoid = 2
          kernel.sysrq = 0

          # Process settings
          fs.file-max = 2097152
          kernel.pid_max = 65536

          # Network settings
          net.ipv4.ip_forward = 0
          net.ipv4.conf.all.rp_filter = 1
          net.ipv4.conf.default.rp_filter = 1
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1

          # File system settings
          fs.protected_hardlinks = 1
          fs.protected_symlinks = 1
          fs.suid_dumpable = 0

    - name: Reload sysctl
      command: sysctl -p
