# --- [R7] --- #

    - name: Enable IOMMU
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash iommu=force"'

    - name: Update Grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      notify:
        - Reboot Server

    - name: Reboot Server
      reboot:

# --- [R7] --- #
