- include_tasks: "4-hardware_configuration/main.yml"
- include_tasks: "5-linux_kernel_configuration/main.yml"
- include_tasks: "6-system_configuration/main.yml"
- include_tasks: "7-services_configuration/main.yml"

- name: Résultat
  debug:
     msg: "Votre machine Linux a bien été configurer !"
  when: LANGUAGE.user_input == "french"

- name: Result
  debug:
     msg: "Your Linux machine has been successfully configured !"
  when: LANGUAGE.user_input == "english"
