    - name: QUESTION - Password Generation
      pause:
        prompt: "[???] In which file do you want to save secure passwords ? (example : /path/to/file/test.txt)"
      register: password_file
      when: LANGUAGE.user_input == "english"

    - name: QUESTION - Génération des mots de passe
      pause:
        prompt: "[???] Dans quelle fichier voulez vous enregistrer les mots de passe sécurisé ? (exemple : /chemin/du/fichier/test.txt)"
      register: password_file
      when: LANGUAGE.user_input == "french"

    - include_tasks: password_generation.yml
