- include_tasks: R61_auto_updates.yml

#- include_tasks: R29_boot_access.yml
#- include_tasks: R34_service_accounts.yml
#- include_tasks: R36_update_MASK.yml
#- include_tasks: R37_MAC_access_control.yml
#- include_tasks: R41_restriction_EXEC.yml
#- include_tasks: R42_remove_negations.yml
#- include_tasks: R45_apparmor_profil.yml
#- include_tasks: R46_SELinux_Targeted.yml
#- include_tasks: R47_access_restrictions_non-privileged_users.yml
#- include_tasks: R49_SELinux_debugging_tools.yml
#- include_tasks: R50_Restrict_access.yml
#- include_tasks: R56_executables_setuid_setgid.yml
#- include_tasks: R57_setuid_setgid_permissions.yml

- name: Résultat
  debug:
     msg: "La configuration du système a été correctement effectuée !"
  when: LANGUAGE.user_input == "french"

- name: Result
  debug:
     msg: "The system configuration has been successfully completed !"
  when: LANGUAGE.user_input == "english"
