- include_tasks: R61_auto_updates.yml

- include_tasks: R29_boot_access.yml
- include_tasks: R34_service_accounts.yml
#- include_tasks: R36_update_MASK.yml
- include_tasks: R37_MAC_access_control.yml
- include_tasks: R38_dedicated_sudo_group.yml
- include_tasks: R39_sudoers_file_permissions.yml
- include_tasks: R40_unprivileged_user.yml
#- include_tasks: R41_restriction_EXEC.yml
- include_tasks: R42_remove_negations.yml
- include_tasks: R43_arguments_sudoers.yml
- include_tasks: R44_secure_file_editing.yml
- include_tasks: R45_apparmor_profil.yml
- include_tasks: R46_SELinux_Targeted.yml
- include_tasks: R47_access_restrictions_non-privileged_users.yml
- include_tasks: R49_SELinux_debugging_tools.yml
- include_tasks: R50_Restrict_access.yml
- include_tasks: R53_files_directories_without_valid_user.yml
- include_tasks: R54_sticky_bit.yml
- include_tasks: R55_separate_temporary_directories.yml
- include_tasks: R56_executables_setuid_setgid.yml
- include_tasks: R57_setuid_setgid_permissions.yml

- name: Résultat
  debug:
     msg: "La configuration du système a été correctement effectuée !"
  when: LANGUAGE.user_input == "french"

- name: Result
  debug:
     msg: "The system configuration has been successfully completed !"
  when: LANGUAGE.user_input == "english"
