- include_tasks: R61_auto_updates.yml


- name: Résultat
  debug:
     msg: "La configuration du système a été correctement effectuée !"
  when: LANGUAGE.user_input == "french"

- name: Result
  debug:
     msg: "The system configuration has been successfully completed !"
  when: LANGUAGE.user_input == "english"
