# --- [R29] --- #

    - name: "Restrict the permissions of the /boot directory"
      ansible.builtin.file:
        path: /boot
        mode: '0700'
        owner: root
        group: root
      state: directory
      recurse: yes
      
# --- [R29] --- #
