# --- [R34] --- #

    - name: Lock service accounts
      user:
        name: "{{ item }}"
        shell: /sbin/nologin
        password_lock: yes
      with_items:
        - nobody
        - daemon
        - bin
        - sys
        - sync
        - games
        - man
        - lp
        - mail
        - news
        - uucp
        - proxy
        - www-data
        - backup
        - list
        - irc
        - gnats
        - nobody
        - systemd-timesync
        - systemd-network
        - systemd-resolve
        - systemd-bus-proxy
        - dbus
        - polkitd
        - tss
 #       - sshd

    - name: Ensure service accounts are disabled in /etc/passwd
      lineinfile:
        path: /etc/passwd
        regexp: '^({{ item }}):'
        line: '\1:x:{{ lookup("file", "/etc/passwd") | regex_search("^({{ item }}):.*$") }}:/sbin/nologin'
      with_items:
        - nobody
        - daemon
        - bin
        - sys
        - sync
        - games
        - man
        - lp
        - mail
        - news
        - uucp
        - proxy
        - www-data
        - backup
        - list
        - irc
        - gnats
        - nobody
        - systemd-timesync
        - systemd-network
        - systemd-resolve
        - systemd-bus-proxy
        - dbus
        - polkitd
        - tss
 #       - sshd
      
# --- [R34] --- #
