# --- [R36] --- #

    - name: Update UMASK in /etc/bashrc
      lineinfile:
        path: /etc/bashrc
        regexp: '^umask'
        line: 'umask 027'
        state: present
        backup: yes
    
    - name: Ensure UMASK is set to 027 in /etc/profile
      lineinfile:
        path: /etc/profile
        regexp: '^umask'
        line: 'umask 027'
        state: present
        backup: yes


    - name: Reload shell configuration
      shell: source /etc/bashrc
      
# --- [R36] --- #
