# --- [R41] --- #

    - name: Add restriction for EXEC commands in sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^Defaults\s+!exec'
        line: 'Defaults !exec'
        #validate: 'visudo -cf %s'
      
# --- [R41] --- #
