# --- [R46] --- #

    - name: Install required SELinux packages
      package:
        name: 
          - libselinux
          - libselinux-utils
          - policycoreutils
        state: present

    - name: Set SELinux policy to targeted
      command: setenforce 1
      # Utilisation de `setenforce` pour appliquer le mode enforcing.
      # `setsebool` est utilisé pour changer les options de booléens de SELinux, pas le mode policy.

    - name: Reboot Server
      reboot:
        msg: "Rebooting to apply SELinux policy changes"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 600

    - name: Ensure SELinux is enabled and set to enforcing
      selinux:
        policy: targeted
        state: enforcing
      
# --- [R46] --- #
