# --- [R53] --- #

    - name: Find files without valid user or group
      find:
        paths: /
        file_type: file
        recurse: yes
        use_regex: no
        patterns: "*"
      register: orphaned_files
      tags:
        - R53

    - name: Report orphaned files
      debug:
        var: orphaned_files
      tags: R53
      
# --- [R53] --- #
