# --- [R54] --- #

- name: Set sticky bit on world-writable directories
  find:
    paths: /
    recurse: yes
    file_type: directory
    mode: "1777"
  register: writable_dirs
  tags: R54

- name: Apply sticky bit to directories
  file:
    path: "{{ item.path }}"
    mode: "1777"
  loop: "{{ writable_dirs.files }}"
  tags: R54
      
# --- [R54] --- #
