# --- [R54] --- #

- name: Find world-writable directories
  command: >
    find / -type d -perm -0002 -exec ls -ld {} +
  register: find_output
  changed_when: false
  tags: R54

- name: Set sticky bit on world-writable directories
  command: >
    chmod +t {{ item }}
  loop: "{{ find_output.stdout_lines }}"
  when: find_output.stdout_lines | length > 0
  tags: R54
      
# --- [R54] --- #
