# --- [R56] --- #

- name: Find and report executables with setuid and setgid bits
  command: find / -type f \( -perm -4000 -o -perm -2000 \) -exec ls -l {} \;
  register: setuid_setgid_files
  ignore_errors: yes

- name: Fail if setuid/setgid files are found
  fail:
    msg: "The following executables with setuid or setgid bits are present: {{ setuid_setgid_files.stdout_lines }}"
  when: setuid_setgid_files.stdout_lines | length > 0
      
# --- [R56] --- #
