# --- [R57] --- #

- name: Find files with setuid or setgid permissions
  command: "find / -type f \\( -perm -4000 -o -perm -2000 \\) -print"
  register: suid_files
  ignore_errors: yes  # En cas d'erreurs comme des permissions insuffisantes

- name: Remove setuid and setgid permissions from found files
  file:
    path: "{{ item }}"
    mode: "u=rwX,g=rX,o=rX"  # Enlève les permissions setuid et setgid
  loop: "{{ suid_files.stdout_lines }}"
  when: suid_files.stdout_lines | length > 0
      
# --- [R57] --- #
