    - name: Disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - dbus
        - hald
        - ConsoleKit
        - CUPS
        - PolicyKit
        - avahi-daemon
        - xorg-x11-server-Xorg
