    - name: Disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - avahi-daemon
        - bluetooth
        - cups
        - ModemManager
        - postfix
        - rpcbind
