- name: Récupérer les informations sur l'espace disque
  command: df -h
  register: disk_info

- name: Afficher les informations sur l'espace disque
  debug:
    msg: "Les informations sur l'espace disque sont : {{ disk_info.stdout_lines }}"
  when: GATHER_INFO_VIEW.user_input in ["oui", "yes"] and LANGUAGE.user_input == "english"
