- name: Gather Facts
  gather_facts:

###---PROMPT---###
- name: Launch English Prompt
  include_tasks: gather_prompt_english.yml

- name: Launch French Prompt
  include_tasks: gather_prompt_french.yml
###---PROMPT---###

- name: Gather OS
  include_tasks: gather_os.yml

- name: Gather Disk Space
  include_tasks: gather_disk_space.yml

- name: Gather Memory
  include_tasks: gather_memory.yml

- name: Gather Processor
  include_tasks: gather_processor.yml

- name: Gather Processus
  include_tasks: gather_process.yml

- name: Gather Network
  include_tasks: gather_network.yml
