- name: Gather Facts
  gather_facts:

###Show_Processor###
- name: Récupérer le type de processeur
  command: lscpu
  register: cpu_info

- name: Afficher le type de processeur
  debug:
    msg: "Le type de processeur est : {{ cpu_info.stdout_lines }}"
###Show_Processor###

###Show_Memory###
- name: Récupérer les informations sur la mémoire
  command: free -m
  register: memory_info

- name: Afficher les informations sur la mémoire
  debug:
    msg: "Les informations sur la mémoire sont : {{ memory_info.stdout_lines }}"
###Show_Memory###

###Show_Space_Disk###
- name: Récupérer les informations sur l'espace disque
  command: df -h
  register: disk_info

- name: Afficher les informations sur l'espace disque
  debug:
    msg: "Les informations sur l'espace disque sont : {{ disk_info.stdout_lines }}"
###Show_Space_Disk###

###Show_Network###
- name: Récupérer les informations sur les interfaces réseau
  command: ip a
  register: network_info

- name: Afficher les informations sur les interfaces réseau
  debug:
    msg: "Les informations sur les interfaces réseau sont : {{ network_info.stdout_lines }}"
###Show_Network###

###Show_Process###
- name: Récupérer la liste des processus en cours
  command: ps aux
  register: processes_info

- name: Afficher la liste des processus en cours
  debug:
    msg: "La liste des processus en cours est : {{ processes_info.stdout_lines }}"
###Show_Process###
