- name: Notify
  block:
    - name: Notification
      debug:
        msg: "This project is presented to you by : Louis PROVOST / Yoan COSTA / Ouail EL GHAZAOUI / Théo BLANCHARD"
      when: LANGUAGE.user_input == "english"

    - name: Notification
      debug:
        msg: "Ce projet vous est présenter par : Louis PROVOST / Yoan COSTA / Ouail EL GHAZAOUI / Théo BLANCHARD"
      when: LANGUAGE.user_input == "french"

- name: "Notify - Link"
  block:
    - name: Notification
      debug:
        msg: "This project is available at : https://github.com/ArtemissFR/DEIMOS_Project"
      when: LANGUAGE.user_input == "english"

    - name: Notification
      debug:
        msg: "Ce projet est disponible via : https://github.com/ArtemissFR/DEIMOS_Project"
      when: LANGUAGE.user_input == "french"
